language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      # The following packages are used for compiling a recent-enough version of kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev

env:
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES=''
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='serde'
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='yolocrypto nightly'
  - TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='nightly bench'
  - TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='yolocrypto nightly bench'
  - TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES='' 

matrix:
  exclude:
    # We can probably remove this, as we reasonably expect dalek to work on
    # stable and beta, but currently we require "test" feature in order to
    # run benchmarks, which causes dalek not to build on stable.  See
    # https://github.com/isislovecruft/curve25519-dalek/pull/38#issuecomment-286027562
    - rust: stable
      env: TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='nightly bench'
    - rust: beta
      env: TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='nightly bench'
    - rust: stable
      env: TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='yolocrypto nightly bench'
    - rust: beta
      env: TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='yolocrypto nightly bench'
    # Test nightly features, such as radix_51, only on nightly.
    - rust: stable
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
    - rust: beta
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
    - rust: stable
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='yolocrypto nightly'
    - rust: beta
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='yolocrypto nightly'
    # Test no_std only on nightly.
    - rust: stable
      env: TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES=''
    - rust: beta
      env: TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES=''
    - rust: nightly
      env: TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES='alloc'

script:
  - cargo $TEST_COMMAND --features="$FEATURES" $EXTRA_FLAGS

after_success:
  - |
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    make install DESTDIR=../../kcov-build &&
    cd ../.. &&
    rm -rf kcov-master &&
    for file in target/debug/curve25519_dalek-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
    bash <(curl -s https://codecov.io/bash) &&
    echo "Uploaded code coverage"

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
